version: '3.9'

services:
  next:
    build: ./next
    container_name: next
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./next:/next
    environment:
     - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    env_file: ./next/src/.env.local
    
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
