import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [file, setFile] = useState<File>();
  const [fileURL, setFileURL] = useState<string>();

  const handleChangeFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]!;
    setFile(file);
    setFileURL(URL.createObjectURL(file));
  };

  const handleFileUpload = async () => {
    if (!file) return;

    const filename = encodeURIComponent(file.name);
    const fileType = encodeURIComponent(file.type);

    console.log(filename, fileType);
  };

  const handleMakeBucket = async () => {
    const post = await fetch("/api/make-bucket", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        bucketName: "test-bucket",
      }),
    });
  };

  return (
    <div>
      <Head>
        <title>Minio Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black text-white shadow-md h-16 flex items-center justify-center">
        <h1 className="text-3xl font-bold">Minio Sample!</h1>
      </div>
      <div className="flex flex-col items-center justify-center gap-3">
        <div className="flex flex-col items-center justify-center my-5 gap-10 bg-gray-100 p-5 rounded-md shadow-md w-4/5">
          <h2 className="text-2xl font-bold">File Uploader</h2>
          <input
            type="file"
            id="avatar"
            name="avatar"
            accept="image/png, image/jpeg"
            onChange={(e) => {
              handleChangeFile(e);
            }}
          ></input>
          <div className="flex flex-col items-center justify-center gap-5 bg-gray-200 p-2 rounded-md shadow-md w-3/5">
            <p>プレビュー</p>
            <img src={fileURL}></img>
          </div>
          <button
            onClick={handleFileUpload}
            className="bg-blue-500 text-white font-bold p-2 rounded-md hover:bg-blue-700"
          >
            Image upload
          </button>
        </div>
        <div className="flex flex-col items-center justify-center my-5 gap-10 bg-gray-100 p-5 rounded-md shadow-md w-4/5">
          <h2 className="text-2xl font-bold">Make Bucket</h2>
          {/* // バケット名を入力するフォーム */}
          <input
            type="text"
            id="bucketName"
            name="bucketName"
            placeholder="Bucket Name"
            className="border-2 border-gray-300 p-2 rounded-md"
          ></input>
          <button
            onClick={handleMakeBucket}
            className="bg-blue-500 text-white font-bold p-2 rounded-md hover:bg-blue-700"
          >
            Make Bucket
          </button>
        </div>
      </div>
    </div>
  );
}
