import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Minio = require('minio')
const minioClient = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: false,
  accessKey: 'nutmeg',
  secretKey: 'gidaifes',
})

export default function Home() {
  const [file, setFile] = useState<File>();
  const [fileURL, setFileURL] = useState<string>();

  const handleChangeFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]!;
    setFile(file);
    setFileURL(URL.createObjectURL(file));
  };

  const handleFileUpload = async () => {
    if (!file) return;

    const filename = encodeURIComponent(file.name);
    const fileType = encodeURIComponent(file.type);
    
    console.log(filename, fileType)
  };

  const handleMakeBucket =async () => {
    const post = await minioClient.makeBucket('mybucket', 'us-east-1', function(err: string) {
      if (err) return console.log('Error creating bucket.', err)
      console.log('Bucket created successfully in "us-east-1".')
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Minio Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Select Image</p>
        <input
          type="file"
          id="avatar"
          name="avatar"
          accept="image/png, image/jpeg"
          onChange={(e) => {
            handleChangeFile(e);
          }}
        ></input>
        <p>プレビュー</p>
        <img src={fileURL}></img>
        <button onClick={handleFileUpload}>Image upload</button>
        <button onClick={handleMakeBucket}>Make Bucket</button>
      </main>
    </div>
  );
}
