version: '3.9'

services:
  next:
    build: ./next
    container_name: next
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./next:/app
    environment:
     - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    env_file: ./next/src/.env.local